# Generated by Django 5.2 on 2026-02-23 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enqueteaccident',
            name='methode_analyse',
            field=models.CharField(blank=True, choices=[('', '—'), ('5p', 'Méthode des 5 Pourquoi'), ('arbre', 'Arbre des causes')], default='', max_length=20),
        ),
        migrations.CreateModel(
            name='Analyse5Pourquoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pourquoi1', models.TextField()),
                ('reponse1', models.TextField()),
                ('pourquoi2', models.TextField()),
                ('reponse2', models.TextField()),
                ('pourquoi3', models.TextField()),
                ('reponse3', models.TextField()),
                ('pourquoi4', models.TextField()),
                ('reponse4', models.TextField()),
                ('pourquoi5', models.TextField()),
                ('reponse5', models.TextField()),
                ('cause_racine_finale', models.TextField()),
                ('maj_le', models.DateTimeField(auto_now=True)),
                ('enquete', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analyse_5p', to='evenements.enqueteaccident')),
            ],
        ),
        migrations.CreateModel(
            name='ArbreCauseNoeud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_noeud', models.CharField(choices=[('fait', 'Fait'), ('cause', 'Cause'), ('barriere', 'Barrière absente')], default='cause', max_length=20)),
                ('description', models.TextField()),
                ('logique', models.CharField(blank=True, choices=[('et', 'ET'), ('ou', 'OU')], max_length=5, null=True)),
                ('ordre', models.PositiveIntegerField(default=1)),
                ('enquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arbre_causes', to='evenements.enqueteaccident')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enfants', to='evenements.arbrecausenoeud')),
            ],
        ),
        migrations.CreateModel(
            name='ChronologieFait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_fait', models.DateField()),
                ('heure_fait', models.TimeField(blank=True, null=True)),
                ('description', models.TextField()),
                ('ordre', models.PositiveIntegerField(default=1)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('enquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chronologie', to='evenements.enqueteaccident')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sous_faits', to='evenements.chronologiefait')),
            ],
            options={
                'ordering': ['date_fait', 'heure_fait', 'ordre', 'id'],
            },
        ),
    ]
