# Generated by Django 5.2 on 2026-02-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenements', '0002_enqueteaccident_methode_analyse_analyse5pourquoi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enqueteaccident',
            name='commentaires_efficacite',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='enqueteaccident',
            name='date_verification_efficacite',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enqueteaccident',
            name='decision_cloture',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='enqueteaccident',
            name='decision_finale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enqueteaccident',
            name='efficace_globale',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
