# Generated by Django 5.2 on 2026-03-09 11:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenements', '0003_enqueteaccident_commentaires_efficacite_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arbrecausenoeud',
            options={'ordering': ['niveau', 'ordre', 'id']},
        ),
        migrations.RenameField(
            model_name='arbrecausenoeud',
            old_name='description',
            new_name='cause',
        ),
        migrations.AddField(
            model_name='arbrecausenoeud',
            name='cree_le',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arbrecausenoeud',
            name='est_cause_racine',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='arbrecausenoeud',
            name='maj_le',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='arbrecausenoeud',
            name='niveau',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='arbrecausenoeud',
            name='pourquoi',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='arbrecausenoeud',
            name='reponse',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='arbrecausenoeud',
            name='type_noeud',
            field=models.CharField(choices=[('fait', 'Fait'), ('cause', 'Cause'), ('barriere', 'Barrière absente'), ('cause_racine', 'Cause racine')], default='cause', max_length=20),
        ),
    ]
