# Generated by Django 5.2 on 2026-03-09 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenements', '0004_alter_arbrecausenoeud_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enqueteaccident',
            name='methode_analyse',
            field=models.CharField(blank=True, choices=[('', '—'), ('5p', 'Méthode des 5P (Personnel, Procédures, Produits, Procédé, Place)'), ('arbre', 'Arbre des causes')], default='', max_length=20),
        ),
        migrations.CreateModel(
            name='Analyse5PIndustrie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personnel', models.TextField()),
                ('procedures', models.TextField()),
                ('produits', models.TextField()),
                ('procede', models.TextField()),
                ('place', models.TextField()),
                ('cause_racine_finale', models.TextField(blank=True)),
                ('recommandations', models.TextField(blank=True)),
                ('maj_le', models.DateTimeField(auto_now=True)),
                ('enquete', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analyse_5p_industrie', to='evenements.enqueteaccident')),
            ],
        ),
    ]
