# Generated by Django 5.2 on 2026-02-19 11:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControleSystemeIncendie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('maj_le', models.DateTimeField(auto_now=True)),
                ('type_systeme', models.CharField(choices=[('alarme', "Système d'alarme"), ('desenfumage', 'Système de désenfumage'), ('alarme_desenfumage', 'Alarme + Désenfumage')], default='alarme_desenfumage', max_length=30)),
                ('date_controle', models.DateField(default=django.utils.timezone.now)),
                ('presence_responsable_securite', models.BooleanField(default=False)),
                ('checklist_alarme', models.JSONField(blank=True, default=dict)),
                ('checklist_desenfumage', models.JSONField(blank=True, default=dict)),
                ('observation', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('conforme', 'Conforme'), ('nc', 'Non conforme'), ('na', 'Non applicable')], default='conforme', max_length=20)),
                ('controle_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controles_systeme_incendie', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles_systemes_incendie', to='sites.site')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controles_systemes_incendie', to='sites.zone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ControleDM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('maj_le', models.DateTimeField(auto_now=True)),
                ('identifiant', models.CharField(max_length=120)),
                ('localisation', models.CharField(blank=True, max_length=255)),
                ('acces_ok', models.BooleanField(default=True)),
                ('etat_ok', models.BooleanField(default=True)),
                ('test_ok', models.BooleanField(default=True)),
                ('remarque', models.TextField(blank=True)),
                ('controle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dms', to='incendie.controlesystemeincendie')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ControleDetecteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('maj_le', models.DateTimeField(auto_now=True)),
                ('identifiant', models.CharField(max_length=120)),
                ('type_detecteur', models.CharField(blank=True, max_length=120)),
                ('localisation', models.CharField(blank=True, max_length=255)),
                ('proprete_ok', models.BooleanField(default=True)),
                ('test_ok', models.BooleanField(default=True)),
                ('remarque', models.TextField(blank=True)),
                ('controle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detecteurs', to='incendie.controlesystemeincendie')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExerciceEvacuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('maj_le', models.DateTimeField(auto_now=True)),
                ('type_exercice', models.CharField(choices=[('planifie', 'Planifié'), ('inopine', 'Inopiné')], default='planifie', max_length=20)),
                ('date_exercice', models.DateField(default=django.utils.timezone.now)),
                ('heure_debut', models.TimeField(blank=True, null=True)),
                ('heure_fin', models.TimeField(blank=True, null=True)),
                ('objectifs', models.TextField(blank=True)),
                ('scenario', models.TextField(blank=True)),
                ('deroulement', models.TextField(blank=True)),
                ('organise_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercices_organises', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercices_evacuation', to='sites.site')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercices_evacuation', to='sites.zone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ControleExerciceEvacuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('maj_le', models.DateTimeField(auto_now=True)),
                ('checklist_declenchement', models.JSONField(blank=True, default=dict)),
                ('checklist_comportement', models.JSONField(blank=True, default=dict)),
                ('checklist_guides', models.JSONField(blank=True, default=dict)),
                ('checklist_issues', models.JSONField(blank=True, default=dict)),
                ('checklist_rassemblement', models.JSONField(blank=True, default=dict)),
                ('temps_total_minutes', models.IntegerField(blank=True, null=True)),
                ('observation', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('conforme', 'Conforme'), ('nc', 'Non conforme'), ('na', 'Non applicable')], default='conforme', max_length=20)),
                ('controle_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controles_exercices', to=settings.AUTH_USER_MODEL)),
                ('exercice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='controle', to='incendie.exerciceevacuation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChronometrageEvacuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('maj_le', models.DateTimeField(auto_now=True)),
                ('libelle_zone', models.CharField(max_length=255)),
                ('heure_debut_zone', models.TimeField(blank=True, null=True)),
                ('heure_arrivee_point', models.TimeField(blank=True, null=True)),
                ('temps_minutes', models.IntegerField(blank=True, null=True)),
                ('remarque', models.TextField(blank=True)),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chronometrages', to='incendie.exerciceevacuation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Extincteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('maj_le', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(max_length=120)),
                ('type_extincteur', models.CharField(max_length=80)),
                ('capacite', models.CharField(blank=True, max_length=40)),
                ('emplacement', models.CharField(max_length=255)),
                ('marque', models.CharField(blank=True, max_length=120)),
                ('numero_serie', models.CharField(blank=True, max_length=120)),
                ('annee_fabrication', models.CharField(blank=True, max_length=10)),
                ('actif', models.BooleanField(default=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extincteurs', to='sites.site')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extincteurs', to='sites.zone')),
            ],
            options={
                'unique_together': {('site', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='ParticipationEvacuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('maj_le', models.DateTimeField(auto_now=True)),
                ('service', models.CharField(max_length=255)),
                ('effectif_theorique', models.IntegerField(default=0)),
                ('presents', models.IntegerField(default=0)),
                ('absents', models.IntegerField(default=0)),
                ('remarque', models.TextField(blank=True)),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='incendie.exerciceevacuation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RapportInterventionIncendie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('maj_le', models.DateTimeField(auto_now=True)),
                ('type_intervention', models.CharField(choices=[('incident', 'Incident réel'), ('exercice', 'Exercice')], default='incident', max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('heure', models.TimeField(blank=True, null=True)),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('actions_menees', models.TextField(blank=True)),
                ('conclusion', models.TextField(blank=True)),
                ('pieces_jointes', models.FileField(blank=True, null=True, upload_to='incendie/rapports/')),
                ('redige_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_incendie', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports_incendie', to='sites.site')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_incendie', to='sites.zone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('maj_le', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(max_length=120)),
                ('localisation', models.CharField(max_length=255)),
                ('type_ria', models.CharField(blank=True, max_length=40)),
                ('diametre_tuyau', models.CharField(blank=True, max_length=40)),
                ('longueur_tuyau', models.CharField(blank=True, max_length=40)),
                ('pression_nominale', models.CharField(blank=True, max_length=40)),
                ('marque', models.CharField(blank=True, max_length=120)),
                ('annee_installation', models.CharField(blank=True, max_length=10)),
                ('actif', models.BooleanField(default=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rias', to='sites.site')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rias', to='sites.zone')),
            ],
            options={
                'unique_together': {('site', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='VerificationExtincteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('maj_le', models.DateTimeField(auto_now=True)),
                ('date_verification', models.DateField(default=django.utils.timezone.now)),
                ('checklist', models.JSONField(blank=True, default=dict)),
                ('statut', models.CharField(choices=[('conforme', 'Conforme'), ('nc', 'Non conforme'), ('na', 'Non applicable')], default='conforme', max_length=20)),
                ('observation', models.TextField(blank=True)),
                ('extincteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='incendie.extincteur')),
                ('verifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifs_extincteurs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VerificationRIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('maj_le', models.DateTimeField(auto_now=True)),
                ('date_verification', models.DateField(default=django.utils.timezone.now)),
                ('checklist_visuelle', models.JSONField(blank=True, default=dict)),
                ('checklist_fonctionnelle', models.JSONField(blank=True, default=dict)),
                ('pression_mesuree', models.CharField(blank=True, max_length=40)),
                ('etancheite_ok', models.BooleanField(default=True)),
                ('statut', models.CharField(choices=[('conforme', 'Conforme'), ('nc', 'Non conforme'), ('na', 'Non applicable')], default='conforme', max_length=20)),
                ('commentaire', models.TextField(blank=True)),
                ('ria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='incendie.ria')),
                ('verifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifs_ria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
