# Generated by Django 5.2 on 2026-02-14 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80)),
                ('prix', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_sites', models.PositiveIntegerField(default=1)),
                ('max_utilisateurs', models.PositiveIntegerField(default=5)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('est_actif', models.BooleanField(default=True)),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='abonnement', to='organisations.organisation')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abonnements.plan')),
            ],
        ),
    ]
