# Generated by Django 5.2 on 2026-02-24 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
        ('sites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=60)),
                ('titre', models.CharField(max_length=255)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('validation', 'En validation'), ('approuve', 'Approuvé'), ('obsolete', 'Obsolète')], default='brouillon', max_length=20)),
                ('version_courante', models.PositiveIntegerField(default=1)),
                ('prochaine_revision', models.DateField(blank=True, null=True)),
                ('derniere_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('mots_cles', models.CharField(blank=True, help_text='Séparés par virgule', max_length=255)),
                ('confidentiel', models.BooleanField(default=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='organisations.organisation')),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents_proprietaire', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='sites.site')),
            ],
            options={
                'ordering': ['-derniere_mise_a_jour'],
            },
        ),
        migrations.CreateModel(
            name='DocumentDiffusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=255)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diffusions', to='documentaire.document')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('fichier', models.FileField(upload_to='qhs/documents/')),
                ('commentaire', models.CharField(blank=True, max_length=255)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents_versions', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documentaire.document')),
            ],
            options={
                'ordering': ['-numero'],
                'unique_together': {('document', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='DocumentActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ouverture', 'Ouverture'), ('telechargement', 'Téléchargement'), ('creation', 'Création'), ('maj', 'Mise à jour'), ('soumission_validation', 'Soumission validation'), ('approbation', 'Approbation'), ('archivage', 'Archivage'), ('diffusion', 'Diffusion'), ('proposition_modif', 'Proposition modification')], max_length=40)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('acteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='documentaire.document')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='documentaire.documentversion')),
            ],
            options={
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='Processus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processus', to='organisations.organisation')),
            ],
            options={
                'ordering': ['nom'],
                'unique_together': {('organisation', 'nom')},
            },
        ),
        migrations.AddField(
            model_name='document',
            name='processus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documentaire.processus'),
        ),
        migrations.CreateModel(
            name='TypeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('actif', models.BooleanField(default=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types_documents', to='organisations.organisation')),
            ],
            options={
                'ordering': ['nom'],
                'unique_together': {('organisation', 'nom')},
            },
        ),
        migrations.AddField(
            model_name='document',
            name='type_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documentaire.typedocument'),
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('organisation', 'code')},
        ),
    ]
