# Generated by Django 5.2 on 2026-02-24 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentaire', '0001_initial'),
        ('organisations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentdiffusion',
            name='cree_par',
        ),
        migrations.RemoveField(
            model_name='documentdiffusion',
            name='document',
        ),
        migrations.AlterUniqueTogether(
            name='typedocument',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='typedocument',
            name='organisation',
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-modifie_le', '-cree_le']},
        ),
        migrations.AlterModelOptions(
            name='documentversion',
            options={'ordering': ['-cree_le']},
        ),
        migrations.RenameField(
            model_name='document',
            old_name='confidentiel',
            new_name='confidentialite',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='prochaine_revision',
            new_name='date_prochaine_revision',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='derniere_mise_a_jour',
            new_name='modifie_le',
        ),

        # ✅ FIX: ajouter les champs AVANT d'appliquer la contrainte unique_together
        migrations.AddField(
            model_name='documentversion',
            name='version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='statut_snapshot',
            field=models.CharField(
                blank=True,
                choices=[
                    ('brouillon', 'Brouillon'),
                    ('validation', 'En validation'),
                    ('approuve', 'Approuvé'),
                    ('obsolete', 'Obsolète'),
                ],
                max_length=20,
                null=True
            ),
        ),
        migrations.AlterUniqueTogether(
            name='documentversion',
            unique_together={('document', 'version')},
        ),

        migrations.AlterField(
            model_name='document',
            name='mots_cles',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='organisation',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='documents_qhs',
                to='organisations.organisation'
            ),
        ),
        migrations.AlterField(
            model_name='document',
            name='proprietaire',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='documents_possedes',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name='document',
            name='version_courante',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='documentaire.documentversion'
            ),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='commentaire',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='cree_par',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='doc_versions_creees',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='fichier',
            field=models.FileField(upload_to='documentaire/documents/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='processus',
            name='nom',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='processus',
            name='organisation',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='processus_docs',
                to='organisations.organisation'
            ),
        ),
        migrations.CreateModel(
            name='DocumentAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', 'Consultation'), ('download', 'Téléchargement'), ('create', 'Création'), ('update_meta', 'Mise à jour fiche'), ('new_version', 'Nouvelle version'), ('status', 'Changement statut'), ('archive', 'Archivage')], max_length=30)),
                ('details', models.CharField(blank=True, max_length=255)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='documentaire.document')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='DocumentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('lu', models.BooleanField(default=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='documentaire.document')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_notifications', to='organisations.organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_types', to='organisations.organisation')),
            ],
            options={
                'ordering': ['nom'],
                'unique_together': {('organisation', 'nom')},
            },
        ),
        migrations.AlterField(
            model_name='document',
            name='type_document',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='documents',
                to='documentaire.documenttype'
            ),
        ),
        migrations.DeleteModel(
            name='DocumentActionLog',
        ),
        migrations.DeleteModel(
            name='DocumentDiffusion',
        ),
        migrations.RemoveField(
            model_name='documentversion',
            name='numero',
        ),
        migrations.DeleteModel(
            name='TypeDocument',
        ),
    ]