# Generated by Django 5.2 on 2026-02-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Administrateur'), ('admin_org', 'Admin Organisation'), ('manager', 'Manager'), ('agent', 'Agent')], default='agent', max_length=20),
        ),
    ]
