# Generated by Django 5.2 on 2026-02-14 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
        ('prestataire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('adresse', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='organisations.organisation')),
            ],
            options={
                'unique_together': {('organisation', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('actif', models.BooleanField(default=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='sites.site')),
            ],
            options={
                'unique_together': {('site', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='AffectationPrestataire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actif', models.BooleanField(default=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('prestataire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affectations', to='prestataire.prestataire')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='sites.site')),
                ('zones', models.ManyToManyField(blank=True, related_name='affectations', to='sites.zone')),
            ],
            options={
                'unique_together': {('site', 'prestataire')},
            },
        ),
    ]
