# Generated by Django 5.2 on 2026-02-16 15:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
        ('prestataire', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prestataire',
            options={'ordering': ['nom']},
        ),
        migrations.AddField(
            model_name='prestataire',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.CreateModel(
            name='DocumentPrestataire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('immatriculation', 'Immatriculation société'), ('niu', 'NIU'), ('autre', 'Autre')], max_length=30)),
                ('titre', models.CharField(blank=True, help_text='Obligatoire si type = Autre (ex: Assurance RC, Contrat, Agrément...)', max_length=255)),
                ('fichier', models.FileField(upload_to='prestataires/documents/')),
                ('date_emission', models.DateField(blank=True, null=True)),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
                ('prestataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='prestataire.prestataire')),
            ],
            options={
                'ordering': ['-date_upload'],
            },
        ),
        migrations.CreateModel(
            name='DomaineIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domaines_prestataires', to='organisations.organisation')),
            ],
            options={
                'ordering': ['nom'],
                'unique_together': {('organisation', 'nom')},
            },
        ),
        migrations.AddField(
            model_name='prestataire',
            name='domaine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prestataires', to='prestataire.domaineintervention'),
        ),
    ]
