# Generated by Django 5.2 on 2026-02-17 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestataire', '0002_alter_prestataire_options_prestataire_date_creation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentPrestataire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('prenom', models.CharField(blank=True, max_length=120)),
                ('telephone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('matricule', models.CharField(blank=True, help_text='Optionnel (matricule interne du prestataire)', max_length=60)),
                ('fonction', models.CharField(blank=True, max_length=120)),
                ('piece_identite', models.CharField(blank=True, max_length=120)),
                ('numero_piece', models.CharField(blank=True, max_length=120)),
                ('date_embauche', models.DateField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('prestataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='prestataire.prestataire')),
            ],
            options={
                'ordering': ['nom', 'prenom'],
                'unique_together': {('prestataire', 'nom', 'prenom', 'telephone')},
            },
        ),
    ]
