# Generated by Django 5.2 on 2026-02-17 01:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
        ('prestataire', '0003_agentprestataire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formations', to='organisations.organisation')),
            ],
            options={
                'ordering': ['nom'],
                'unique_together': {('organisation', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='SessionFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=255)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('duree_minutes', models.PositiveIntegerField(default=0)),
                ('lieu', models.CharField(blank=True, max_length=255)),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('encours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='planifiee', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='permis.formation')),
                ('intervenants', models.ManyToManyField(blank=True, related_name='sessions_animees', to='prestataire.agentprestataire')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_formations', to='organisations.organisation')),
            ],
            options={
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='TypeHabilitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('formations_requises', models.ManyToManyField(blank=True, related_name='habilitations_delivrees', to='permis.formation')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types_habilitations', to='organisations.organisation')),
            ],
            options={
                'ordering': ['nom'],
                'unique_together': {('organisation', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='ParticipantSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(default=True)),
                ('valide', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=30)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_suivies', to='prestataire.agentprestataire')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='permis.sessionformation')),
            ],
            options={
                'unique_together': {('session', 'agent')},
            },
        ),
        migrations.CreateModel(
            name='AgentHabilitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_obtention', models.DateField(default=django.utils.timezone.now)),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('preuve', models.FileField(blank=True, null=True, upload_to='habilitations/preuves/')),
                ('actif', models.BooleanField(default=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilitations', to='prestataire.agentprestataire')),
                ('type_habilitation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agents', to='permis.typehabilitation')),
            ],
            options={
                'ordering': ['-date_obtention'],
                'unique_together': {('agent', 'type_habilitation')},
            },
        ),
    ]
