# Generated by Django 5.2 on 2026-02-17 21:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
        ('permis', '0001_initial'),
        ('prestataire', '0003_agentprestataire'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypePermis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('habilitations_requises', models.ManyToManyField(blank=True, related_name='permis_eligibles', to='permis.typehabilitation')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types_permis', to='organisations.organisation')),
            ],
            options={
                'ordering': ['nom'],
                'unique_together': {('organisation', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('lieu', models.CharField(blank=True, max_length=255)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('encours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='planifiee', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agents', models.ManyToManyField(blank=True, related_name='interventions', to='prestataire.agentprestataire')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='organisations.organisation')),
                ('permis_requis', models.ManyToManyField(blank=True, related_name='interventions', to='permis.typepermis')),
            ],
            options={
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='PermisDelivre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_delivrance', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_expiration', models.DateTimeField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('remarque', models.TextField(blank=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permis_delivres', to='prestataire.agentprestataire')),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permis_delivres', to='permis.intervention')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permis_delivres', to='organisations.organisation')),
                ('type_permis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivrances', to='permis.typepermis')),
            ],
            options={
                'ordering': ['-date_delivrance'],
                'unique_together': {('intervention', 'agent', 'type_permis')},
            },
        ),
    ]
