# Generated by Django 5.2 on 2026-02-17 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permis', '0002_typepermis_intervention_permisdelivre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='permisdelivre',
            name='motif_refus',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='permisdelivre',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('refuse', 'Refusé')], default='en_attente', max_length=20),
        ),
        migrations.AddField(
            model_name='permisdelivre',
            name='valide_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='permisdelivre',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permis_valides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='permisdelivre',
            name='date_delivrance',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='QuestionPermis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=500)),
                ('type_reponse', models.CharField(choices=[('bool', 'Oui / Non'), ('text', 'Texte'), ('choice', 'Choix'), ('number', 'Nombre')], default='bool', max_length=20)),
                ('choix', models.TextField(blank=True, help_text='Ex: OK; KO; N/A')),
                ('obligatoire', models.BooleanField(default=True)),
                ('ordre', models.PositiveIntegerField(default=1)),
                ('actif', models.BooleanField(default=True)),
                ('type_permis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='permis.typepermis')),
            ],
            options={
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReponsePermis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur_bool', models.BooleanField(blank=True, null=True)),
                ('valeur_text', models.TextField(blank=True)),
                ('valeur_choice', models.CharField(blank=True, max_length=255)),
                ('valeur_number', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('remarque', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('permis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='permis.permisdelivre')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reponses', to='permis.questionpermis')),
            ],
            options={
                'ordering': ['question__ordre', 'id'],
                'unique_together': {('permis', 'question')},
            },
        ),
    ]
